name = "exam-worker"
main = "src/index.ts"
compatibility_date = "2023-07-19"

[vars]
SUPABASE_URL = "https://bjrmgkbovgqjaheuvkqa.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqcm1na2JvdmdxamFoZXV2a3FhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMjQwMjg3NCwiZXhwIjoyMDQ3OTc4ODc0fQ.T7Xru1VsvLfz8DUtwFALGaXi_SNP6XRg8nJqpft1-PY"
